version: 1.0.{build}
build_script:
- ps: .\build.ps1 $env:APPVEYOR_BUILD_VERSION
test_script:
- ps: .\RunTests.ps1
notifications:
- provider: Webhook
  url: http://104.45.24.179:8080/appveyor
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
